name: Rebase to main_huawei

on:
  push:
    branches:
      - main
      
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Merge main -> main_unity
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main_unity
          github_token: ${{ github.token }}
          message: 'Auto merge by git hub actions'