name: auto-build

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    - "Structures-(NetSixZero|NetStandard)"
    - "lock"
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: set WORK_DIR variable from tag
      run: echo "WORK_DIR=${GITHUB_REF/refs\/tags\/Structures-/}" >> $GITHUB_ENV
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION} --no-restore --verbosity normal
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push NuGet.${WORK_DIR}.${VERSION}.nupkg --source https://nuget.pkg.github.com/Gr8-Tools/index.json --api-key ${GITHUB_TOKEN}
      
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
