name: Unity Tests

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  tests:
    if: contains(github.head_ref, 'unity')
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.3.24f1
        projectPath:
          - Unity/Structrues-Unity

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
          
      # Cache
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library # Unity/Structrues-Unity/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }} # Library-${{ runner.os }}-${{ hashFiles('Unity/Structrues-Unity/**/*.cs') }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
# Library-${{ runner.os }}-
          
      # Project Tests
      - name: Project Tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          testMode : 'editmode'
          projectPath: ${{ matrix.projectPath }} # Unity/Structrues-Unity
          githubToken: ${{ secrets.GITHUB_TOKEN }}
