name: Unity Release

on:
  push:
    branches:
      - main
    
jobs:
  upm-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create Release for OpenUPM
      id: create_release
      uses: quabug/create-upm-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        target: main_unity
        upm_tag_prefix: v
        upm_package_path: Unity/Structrues-Unity/Packages/Structures-Unity
        create_unitypackage: true
        unitypackage_name: Structures-Unity