name: Unity Tests Manual

on:
  workflow_dispatch: {}

jobs:
  tests:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        # with:
          # lfs: true
          
      # Project Tests
      - name: Project Tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          testMode : 'editmode'
          projectPath: Unity/Structrues-Unity
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          
      # # Package Tests
      # - name: Package Tests
        # uses: game-ci/unity-test-runner@v2
        # env:
          # UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        # with:
          # projectPath: Unity/Structrues-Unity/Packages/Structures-Unity
          # githubToken: ${{ secrets.GITHUB_TOKEN }}
    
