name: Unity Tests

on:
  push:
    branches: [ "main_unity" ]
  pull_request:
    branches: [ "main_unity" ]

jobs:
  tests:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        # with:
          # lfs: true
          
      # Cache
      - uses: actions/cache@v2
        with:
          path: Unity/Structrues-Unity/Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
          
      # Project Tests
      - name: Project Tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          testMode : 'editmode'
          projectPath: Unity/Structrues-Unity
          githubToken: ${{ secrets.GITHUB_TOKEN }}